#!/bin/bash

# Get the password for the MySQL root user
PASSWORD="$1"

# Get the current date
DATE=$(date +"%d-%m-%Y")

# Dump all databases to the backup.sql file
mysqldump -u root -p"$PASSWORD" --all-databases > backup.sql

# Compress the backup.sql file to a tar.gz archive
tar -czvf "$DATE.tar.gz" backup.sql

# Remove the backup.sql file
rm backup.sql
